/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import music.MP3Player;
import pictures.ImageLoader;
import pictures.Pictures;

/**
 * Main menue
 * @author Paul
 */
public class Menue extends JFrame implements ActionListener{

    private ImageIcon icon;
    private JLabel dino;
    private MP3Player player;
    private ImageLoader loader;
    
    /**
     * Creates new form Menue
     */
    public Menue() {
        this.loader = pictures.ImageLoader.getInstance();
        this.setUndecorated(true);
        this.setSize(1500, 1000);
        this.setResizable(false);
        this.setContentPane(new JLabel(new ImageIcon(this.loader.getImage(Pictures.Normal))));
        this.initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        anleitung = new javax.swing.JButton();
        close = new javax.swing.JButton();
        highscore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        play.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        play.setText("Spielen");

        anleitung.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        anleitung.setText("Anleitung");

        close.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        close.setText("Schließen");

        highscore.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        highscore.setText("Highscore");

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("LITTLE DRAGON WALK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highscore, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(anleitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(593, 593, 593))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anleitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(highscore, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        play.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *  inits the form
     */
    public void init(){
        this.loader = pictures.ImageLoader.getInstance();
        this.icon = this.loader.getImageIcon(Pictures.Menue);
        this.dino = new JLabel(icon);
        this.dino.setBounds(100, 500, this.icon.getIconWidth(), this.icon.getIconHeight());
        this.add(this.dino);
        this.dino = new JLabel(icon);
        this.dino.setBounds(this.getWidth() - this.icon.getIconWidth() - 100, 500, this.icon.getIconWidth(), this.icon.getIconHeight());
        this.add(this.dino);
        this.player = new music.MP3Player("music/files/Stuck.mp3");
        this.player.play();
        this.play.addActionListener(this);
        this.anleitung.addActionListener(this);
        this.highscore.addActionListener(this);
        this.close.addActionListener(this);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menue().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anleitung;
    private javax.swing.JButton close;
    private javax.swing.JButton highscore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables

    /**
     * KeyListener
     * @param e ActionEvent
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(this.anleitung)){
            Instructions anleitung = new Instructions();
            this.player.stop();
            this.setVisible(false);
            anleitung.setVisible(true);
        }
        
        if (e.getSource().equals(this.play)){
            this.player.stop();
            this.setVisible(false);
            Game game = new Game();
            game.setVisible(true);
        }
        
        if (e.getSource().equals(this.highscore)){
            Highscore score = new Highscore();
            this.player.stop();
            this.setVisible(false);
            score.setVisible(true);
        }
        
        if (e.getSource().equals(this.close)){
            this.player.stop();
            this.setVisible(false);
            System.exit(0);
        }
        
    }
}
